# Generated by Django 4.2.3 on 2023-08-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_name', models.CharField(max_length=100)),
                ('switch_type', models.IntegerField()),
                ('switch_id', models.UUIDField()),
                ('host_name', models.CharField(max_length=100)),
                ('adapter_name', models.CharField(max_length=100)),
                ('allow_host_use_adapter', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_name', models.CharField(max_length=100)),
                ('switch_type', models.IntegerField()),
                ('switch_id', models.UUIDField()),
                ('host_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_name', models.CharField(max_length=100)),
                ('switch_type', models.IntegerField()),
                ('switch_id', models.UUIDField()),
                ('host_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
